rtl/earth_top.v
rtl/acc_16_1.v
rtl/acc_temporal.v
rtl/arith_pipeline.v
rtl/dpu.v
rtl/fp16_adder.v
rtl/fp16_mul.v
rtl/lut_bank.v
rtl/output_collector.v
rtl/pe_array.v
rtl/token_buffer.v
rtl/weight_buffer.v
rtl/acc_array.v
rtl/act_dispatcher.v
rtl/buffer.v
rtl/fp16_acc.v
rtl/fp16_int4_mul.v
rtl/gating.v 
rtl/main_controller.v
rtl/pe.v
rtl/sram16_wrapper.v
rtl/topk.v
rtl/weight_dispatcher.v